import ee

# Try to Initialize Earth Engine API and if it fails Authentication is needed first.
try:
    ee.Initialize()
except:
    ee.Authenticate()
    ee.Initialize()


# -------------------------------------- #
# ---------- Table of Context ---------- #
# -------------------------------------- #
'''
1. Create Internal Variables
2. Create Variables
3. Create Internal Functions
4. Create Functions
'''
# -------------------------------------- #

# -------------------------------------------------- #
# ---------- 1. Create Internal Variables ---------- #
# -------------------------------------------------- #

# ----------------------------------------- #
# ---------- 2. Create Variables ---------- #
# ----------------------------------------- #

GSV_DS_LANDSAT_1_COLLECTION_ID = 'LANDSAT/LM01/C01/T1'
GSV_DS_LANDSAT_2_COLLECTION_ID = 'LANDSAT/LM02/C01/T1'
GSV_DS_LANDSAT_3_COLLECTION_ID = 'LANDSAT/LM03/C01/T1'
GSV_DS_LANDSAT_4_COLLECTION_ID = 'LANDSAT/LM04/C01/T1'
GSV_DS_LANDSAT_5_COLLECTION_ID = 'LANDSAT/LM05/C01/T1'
GSV_DS_LANDSAT_7_COLLECTION_ID = 'LANDSAT/LM07/C01/T1'
GSV_DS_LANDSAT_8_COLLECTION_ID = 'LANDSAT/LM08/C01/T1'

GSV_DS_LANDSAT_4_SR_COLLECTION_ID = "LANDSAT/LT04/C01/T1_SR"
GSV_DS_LANDSAT_4_TOA_COLLECTION_ID = "LANDSAT/LT04/C01/T1_TOA"
GSV_DS_LANDSAT_4_LT_RAW_COLLECTION_ID = "LANDSAT/LT04/C01/T1"

GSV_DS_LANDSAT_4_8DAY_BAI_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_BAI"
GSV_DS_LANDSAT_4_8DAY_EVI_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_EVI"
GSV_DS_LANDSAT_4_8DAY_NDVI_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_NDVI"
GSV_DS_LANDSAT_4_8DAY_NBRT_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_NBRT"
GSV_DS_LANDSAT_4_8DAY_NDSI_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_NDSI"
GSV_DS_LANDSAT_4_8DAY_NDWI_COLLECTION_ID = "LANDSAT/LT04/C01/T1_8DAY_NDWI"

GSV_DS_LANDSAT_5_SR_COLLECTION_ID = "LANDSAT/LT05/C01/T1_SR"
GSV_DS_LANDSAT_5_TOA_COLLECTION_ID = "LANDSAT/LT05/C01/T1_TOA"
GSV_DS_LANDSAT_5_LT_RAW_COLLECTION_ID = "LANDSAT/LT05/C01/T1"

GSV_DS_LANDSAT_5_8DAY_BAI_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_BAI"
GSV_DS_LANDSAT_5_8DAY_EVI_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_EVI"
GSV_DS_LANDSAT_5_8DAY_NDVI_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_NDVI"
GSV_DS_LANDSAT_5_8DAY_NBRT_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_NBRT"
GSV_DS_LANDSAT_5_8DAY_NDSI_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_NDSI"
GSV_DS_LANDSAT_5_8DAY_NDWI_COLLECTION_ID = "LANDSAT/LT05/C01/T1_8DAY_NDWI"

GSV_DS_LANDSAT_7_SR_COLLECTION_ID = "LANDSAT/LE07/C01/T1_SR"
GSV_DS_LANDSAT_7_TOA_COLLECTION_ID = "LANDSAT/LE07/C01/T1_TOA"
GSV_DS_LANDSAT_7_LT_RAW_COLLECTION_ID = "LANDSAT/LE07/C01/T1"

GSV_DS_LANDSAT_7_8DAY_BAI_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_BAI"
GSV_DS_LANDSAT_7_8DAY_EVI_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_EVI"
GSV_DS_LANDSAT_7_8DAY_NDVI_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_NDVI"
GSV_DS_LANDSAT_7_8DAY_NBRT_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_NBRT"
GSV_DS_LANDSAT_7_8DAY_NDSI_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_NDSI"
GSV_DS_LANDSAT_7_8DAY_NDWI_COLLECTION_ID = "LANDSAT/LE07/C01/T1_8DAY_NDWI"



# -------------------------------------------------- #
# ---------- 3. Create Internal Functions ---------- #
# -------------------------------------------------- #

# ----------------------------------------- #
# ---------- 4. Create Functions ---------- #
# ----------------------------------------- #
